# Generated by Django 3.1.4 on 2020-12-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'tbl_curso',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(default='SN', max_length=10, null=True),
        ),
    ]
