# Generated by Django 3.1.4 on 2020-12-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='formacao',
            field=models.ManyToManyField(db_table='tbl_pessoa_curso', to='api.Curso'),
        ),
        migrations.AlterModelTable(
            name='profissional',
            table='tbl_profissional',
        ),
    ]
