# Generated by Django 3.1.4 on 2020-12-30 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='formacao',
        ),
        migrations.CreateModel(
            name='PessoaCurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.curso')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.profissional')),
            ],
            options={
                'verbose_name': 'PessoaCurso',
                'verbose_name_plural': 'PessoaCursos',
                'db_table': 'tbl_pessoa_curso',
                'managed': True,
                'unique_together': {('profissional', 'curso')},
            },
        ),
    ]
