# Generated by Django 3.1.4 on 2020-12-30 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201230_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoacurso',
            old_name='curso',
            new_name='curso_id',
        ),
        migrations.RenameField(
            model_name='pessoacurso',
            old_name='profissional',
            new_name='profissional_id',
        ),
        migrations.AlterUniqueTogether(
            name='pessoacurso',
            unique_together={('profissional_id', 'curso_id')},
        ),
    ]
