# Generated by Django 3.1.4 on 2020-12-30 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201230_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.curso'),
        ),
        migrations.AlterField(
            model_name='pessoacurso',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.curso'),
        ),
    ]
