# Generated by Django 3.1.4 on 2020-12-30 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201230_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.endereco'),
        ),
    ]
