# Generated by Django 3.1.4 on 2020-12-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profissional_endereco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nome',
            new_name='curso_nome',
        ),
    ]
